import Link from "next/link";
import { addStudents, moveStudents, resetAssignments, savePreset, setArchived, updateClassroom } from "@/app/actions";
import { requireTeacher } from "@/lib/auth";
import { ownedClassroom } from "@/lib/classes";
import { db } from "@/lib/db";
import { CsvNames } from "@/components/CsvNames";

export default async function Roster({ params, searchParams }: { params: Promise<{ classroomId: string }>; searchParams: Promise<{ sort?: string }> }) {
  const teacher = await requireTeacher(); const { classroomId } = await params; const classroom = await ownedClassroom(teacher.id, classroomId);
  const students = await db.student.findMany({ where: { classroomId, teacherId: teacher.id }, include: { transactions: { select: { amount: true } }, assignments: { where: { endedAt: null }, include: { card: true } } } });
  const rows = students.map((student) => ({ ...student, balance: student.transactions.reduce((sum, item) => sum + item.amount, 0) }));
  const sort = (await searchParams).sort;
  rows.sort(sort === "balance" ? (a, b) => b.balance - a.balance : (a, b) => a.displayName.localeCompare(b.displayName));
  const destinations = await db.classroom.findMany({ where: { teacherId: teacher.id, archived: false, NOT: { id: classroomId } } });
  const presets = await db.awardPreset.findMany({ where: { classroomId }, orderBy: { sortOrder: "asc" } });
  return <div className="grid gap-6"><div><p className="font-bold text-[#e85d43]">{classroom.name}</p><h1 className="text-4xl">Roster</h1></div>
    <div className="flex gap-2"><Link className="btn btn-soft" href={`?sort=name`}>Sort A-Z</Link><Link className="btn btn-soft" href={`?sort=balance`}>Sort by balance</Link><a className="btn" href={`/api/export/${classroomId}`}>Export transactions</a></div>
    {!classroom.archived && <details className="panel p-5"><summary className="font-bold">Bulk add students</summary><form action={addStudents} className="mt-4 grid gap-3"><input type="hidden" name="classroomId" value={classroomId} /><label className="label">Student names<textarea className="field min-h-36" name="names" placeholder="Avery Johnson, Sam Rivera, Jordan Lee" required /></label><p className="text-sm text-slate-600">Separate names with commas or put one name on each line.</p><CsvNames /><button className="btn btn-accent">Add students</button></form></details>}
    <form action={moveStudents} className="panel overflow-hidden"><div className="grid gap-3 border-b border-black/10 p-4 md:grid-cols-[1fr_240px_auto]"><strong>Select students to move</strong><select className="field" name="destinationId" required><option value="">Destination class</option>{destinations.map((room) => <option value={room.id}>{room.name}</option>)}</select><button className="btn">Move selected</button></div>{rows.map((student) => <label className="grid min-h-16 cursor-pointer grid-cols-[auto_1fr_auto_auto] items-center gap-4 border-b border-black/5 px-4" key={student.id}><input type="checkbox" name="studentIds" value={student.id} /><span><Link className="font-bold underline" href={`/app/student/${student.id}`}>{student.displayName}</Link>{!student.active && <small className="ml-2 text-red-700">Inactive</small>}</span><span className="display text-xl">{classroom.currencySymbol}{student.balance}</span><span className="text-sm">{student.assignments[0] ? `Card ${student.assignments[0].card.label}` : "No card"}</span></label>)}{!rows.length && <p className="p-8 text-center">No students are in this classroom.</p>}</form>
    <details className="panel p-5"><summary className="font-bold">Classroom settings</summary><form action={updateClassroom} className="mt-4 grid gap-3 md:grid-cols-5"><input type="hidden" name="classroomId" value={classroomId} /><input className="field" name="name" defaultValue={classroom.name} required /><input className="field" name="schoolYear" defaultValue={classroom.schoolYear} required /><input className="field" name="currencyName" defaultValue={classroom.currencyName} required /><input className="field" name="currencySymbol" defaultValue={classroom.currencySymbol} required /><button className="btn">Save</button></form><h3 className="mt-6 text-lg">Award presets</h3><div className="mt-2 grid gap-2">{presets.map((preset) => <form action={savePreset} className="grid gap-2 md:grid-cols-[1fr_100px_100px_auto]" key={preset.id}><input type="hidden" name="classroomId" value={classroomId} /><input type="hidden" name="presetId" value={preset.id} /><input className="field" name="label" defaultValue={preset.label} /><input className="field" name="amount" type="number" min="1" defaultValue={preset.amount} /><input className="field" name="sortOrder" type="number" defaultValue={preset.sortOrder} /><button className="btn btn-soft">Save</button></form>)}{!classroom.archived && <form action={savePreset} className="grid gap-2 md:grid-cols-[1fr_100px_100px_auto]"><input type="hidden" name="classroomId" value={classroomId} /><input className="field" name="label" placeholder="New preset" required /><input className="field" name="amount" type="number" min="1" placeholder="Amount" required /><input className="field" name="sortOrder" type="number" defaultValue={presets.length} /><button className="btn">Add</button></form>}</div><div className="mt-5 flex flex-wrap gap-3"><form action={setArchived}><input type="hidden" name="classroomId" value={classroomId} /><input type="hidden" name="archived" value={String(!classroom.archived)} /><button className="btn btn-soft">{classroom.archived ? "Restore classroom" : "Archive classroom"}</button></form><form action={resetAssignments}><input type="hidden" name="classroomId" value={classroomId} /><button className="btn bg-red-700">End all card assignments</button></form></div></details>
  </div>;
}
