import Link from "next/link";
import { assignCard, autoAssign, createCardBatch, resetAssignments } from "@/app/actions";
import { requireTeacher } from "@/lib/auth";
import { ownedClassroom } from "@/lib/classes";
import { db } from "@/lib/db";
import { BulkCardManager } from "@/components/BulkCardManager";

export default async function Cards({ params }: { params: Promise<{ classroomId: string }> }) {
  const teacher = await requireTeacher(); const { classroomId } = await params; const classroom = await ownedClassroom(teacher.id, classroomId);
  const [students, cards] = await Promise.all([
    db.student.findMany({ where: { teacherId: teacher.id, classroomId, active: true }, orderBy: { displayName: "asc" }, include: { assignments: { where: { endedAt: null }, include: { card: true } } } }),
    db.card.findMany({ where: { teacherId: teacher.id }, include: { assignments: { where: { endedAt: null }, include: { student: { include: { classroom: true } } } } } }),
  ]);
  cards.sort((first, second) => Number(first.label) - Number(second.label) || first.label.localeCompare(second.label, undefined, { numeric: true }));
  const available = cards.filter((card) => card.status === "AVAILABLE"); const unassigned = students.filter((student) => !student.assignments.length);
  const counts = { available: cards.filter((card) => card.status === "AVAILABLE").length, assigned: cards.filter((card) => card.status === "ASSIGNED").length, lost: cards.filter((card) => card.status === "LOST").length, retired: cards.filter((card) => card.status === "RETIRED").length };
  return <div className="grid gap-6"><div><p className="font-bold text-[#e85d43]">Reusable card set</p><h1 className="text-4xl">Cards for {classroom.name}</h1><p className="mt-2 max-w-3xl text-slate-600">A permanent URL belongs to each numbered card, not to a student. Write Card #1’s URL to physical Card #1 once. When you assign Card #1 below, that same URL immediately opens the assigned student. Reassigning it later requires no NFC rewrite.</p></div>
    <div className="panel grid gap-3 p-5 md:grid-cols-3"><Link className="rounded-xl bg-[#fff0e8] p-4" href={`/app/class/${classroomId}/cards/encoding`}><strong className="block text-lg">1. Write NFC cards</strong><span className="text-sm">Copy each URL into NFC Tools.</span></Link><Link className="rounded-xl bg-[#cde7d8] p-4" href={`/app/class/${classroomId}/cards/print`}><strong className="block text-lg">2. Print QR labels</strong><span className="text-sm">Match QR, short code, and card number.</span></Link><div className="rounded-xl bg-black/5 p-4"><strong className="block text-lg">3. Assign students</strong><span className="text-sm">Choose the numbered card beside each student below.</span></div></div>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-4"><div className="panel p-4"><p className="text-sm text-slate-500">Available</p><p className="display text-3xl">{counts.available}</p></div><div className="panel p-4"><p className="text-sm text-slate-500">Assigned</p><p className="display text-3xl">{counts.assigned}</p></div><div className="panel p-4"><p className="text-sm text-slate-500">Lost</p><p className="display text-3xl">{counts.lost}</p></div><div className="panel p-4"><p className="text-sm text-slate-500">Retired</p><p className="display text-3xl">{counts.retired}</p></div></section>
    {!classroom.archived && <form action={createCardBatch} className="panel flex flex-wrap items-end gap-3 p-5"><label className="label">New cards<input className="field max-w-32" type="number" name="count" min="1" max="200" defaultValue="30" required /></label><button className="btn btn-accent">Generate card set</button><span className="text-sm text-slate-600">Permanent tokens and labels continue from the highest existing number.</span></form>}
    <section className="grid gap-4 lg:grid-cols-2"><div className="panel p-5"><h2 className="text-2xl">Students without cards <span className="text-[#e85d43]">{unassigned.length}</span></h2><p className="mt-1 text-sm text-slate-600">Select the number printed on the physical card you are handing to each student.</p><div className="mt-4 grid gap-2">{unassigned.map((student) => <form action={assignCard} className="grid grid-cols-[1fr_150px_auto] items-center gap-2" key={student.id}><input type="hidden" name="studentId" value={student.id} /><strong>{student.displayName}</strong><select className="field" name="cardId" required><option value="">Physical card...</option>{available.map((card) => <option value={card.id} key={card.id}>Card #{card.label} · {card.shortCode}</option>)}</select><button className="btn">Assign</button></form>)}{!unassigned.length && <p className="text-green-700">Every active student has a card.</p>}</div></div>
      <div className="panel p-5"><h2 className="text-2xl">Free cards <span className="text-[#e85d43]">{available.length}</span></h2><div className="mt-4 flex flex-wrap gap-2">{available.map((card) => <span className="rounded-lg bg-[#cde7d8] px-3 py-2 font-bold" key={card.id}>#{card.label} · {card.shortCode}</span>)}{!available.length && <p>No cards are currently available.</p>}</div></div></section>
    {!classroom.archived && <div className="flex flex-wrap gap-3"><form action={autoAssign}><input type="hidden" name="classroomId" value={classroomId} /><button className="btn btn-accent">Sequential auto-assign</button></form><form action={resetAssignments}><input type="hidden" name="classroomId" value={classroomId} /><button className="btn bg-red-700">End all assignments in this class</button></form></div>}
    <BulkCardManager cards={cards.map((card) => ({ id: card.id, label: card.label, shortCode: card.shortCode, status: card.status, studentName: card.assignments[0]?.student.displayName ?? null, studentClassroom: card.assignments[0]?.student.classroom?.name ?? null }))} />
  </div>;
}
